#version info
#Thu Aug 24 16:47:54 CST 2017
sar=edas.sar.dev.V2.8.2
pandora=2.0.7
edas-assist=1.4
pandora-qos-service=2.1.1
spas-sdk-client=1.2.4.legacy-SNAPSHOT
eagleeye-core=1.4.8
diamond-client=3.7.2.5
spas-sdk-service=1.2.4.legacy-SNAPSHOT
config-client=2.0.1-edas-SNAPSHOT
unitrouter=1.0.11
sentinel-plugin=2.0.9
hsf=edas.hsf.2114.1.0
